name: "useful-tagger"
description: "A practical issue tagging program"
branding:
  icon: award
  color: green
author: 'CoolPlayLin'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
  path:
    description: 'The path to the configuration file'
    required: false
    default: ""
  default-tag:
    description: 'The label used when all labels do not match'
    required: false
    default: 'triage-needed'
  removeAllTags:
    description: 'Remove all tags before adding tags'
    required: false
    default: 'false'
  debug:
    description: "Only Use for develop"
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'