name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [master]

permissions:
  issues: write
  pull-requests: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 19, 20]
        os: [ubuntu-latest]
    steps:
      - name: Checkout in ${{ matrix.os }}
        uses: actions/checkout@master
      - name: Setup Node ${{ matrix.node }} environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Comment
        if: failure()
        uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@${{ github.event.pull_request.user.login }},\nCheck in ${{ matrix.os }} with node.js ${{ matrix.node }} has been failed\nPlease check your code.",
              pull_number: context.payload.pull_request.number,
              event: "REQUEST_CHANGES"
            })
  OwnerApprove:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Approve CoolPlayLin
        if: github.event.pull_request.user.login == 'coolplaylin'
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@${{ github.event.pull_request.user.login }},\nYour pull request has been automatically approved",
              pull_number: context.payload.pull_request.number,
              event: "APPROVE"
            })
      - name: Approve Dependabot
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@${{ github.event.pull_request.user.login }},\nYour pull request has been automatically approved by us",
              pull_number: context.payload.pull_request.number,
              event: "APPROVE"
            })
      - name: Approve Renovate
        if: github.event.pull_request.user.login == 'renovate[bot]'
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@${{ github.event.pull_request.user.login }},\nYour pull request has been automatically approved by us",
              pull_number: context.payload.pull_request.number,
              event: "APPROVE"
            })
  ActionApprove:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Approve
        if: github.event.pull_request.user.login != 'github-actions[bot]'
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@${{ github.event.pull_request.user.login }},\nAll check has been passed",
              pull_number: context.payload.pull_request.number,
              event: "APPROVE"
            })
  AutoApprove:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'coolplaylinbot'
    steps:
      - name: Approve (Owner)
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: "APPROVE"
            })
      - name: Approve (Owner)
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.COOLPLAYLIN_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: "APPROVE"
            })
      - name: Auto Merge
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
