name: CI

on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
  if: github.event.pusher.name != vars.COOLPLAYLIN_BOT_NAME
  strategy:
    matrix:
      node: [16, 17, 18, 19, 20]
  steps:
   - name: Checkout
     uses: actions/checkout@master
   - name: Setup Node ${{ matrix.node }} environment
     uses: actions/setup-node@v2.5.2
     with:
        node-version: ${{ matrix.node }}
   - name: Install dependencies
     run: npm install
   - name: Build
     run: npm run build