name: Formater

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
 build:
  
  runs-on: ubuntu-latest
  if: github.event.pusher.name != vars.COOLPLAYLIN_BOT_NAME
  steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
    - name: Set up Information
      run: |
       git config --global user.email ${{ vars.COOLPLAYLIN_BOT_EMAIL }}
       git config --global user.name ${{ vars.COOLPLAYLIN_BOT_NAME }}
    - name: Delete old dist folder
      if: github.event_name != 'push'
      run: |
       if [ -d "dist" ]; then
       rm -rf "dist"
       fi
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build dist file
      if: github.event_name != 'push'
      run: |
       npm run build
       git add dist --force
       if [[ -n $(git status -s) ]]; then
       git commit -m "[Automated] Update dist file"
       fi
    - name: Format
      run: |
       npm run format:w
       git add .
       if [[ -n $(git status -s) ]]; then
       git commit -m "[Automated] Format All of the file"
       fi
    - name: Push to master branch
      run: git push origin master --force