name: Auto Push

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  if: github.event.pusher.name != 'coolplaylinbot'
  steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
    - name: Set up Information
      run: |
       git config --global user.email "130831920+coolplaylinbot@users.noreply.github.com"
       git config --global user.name "coolplaylinbot"
    - name: Delete
      if: github.event_name != 'push'
      run: |
       if [ -d "dist" ]; then
       rm -rf "dist"
       fi
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build
      if: github.event_name != 'push'
      run: npm run build
    - name: Format
      run: npm run format:w
    - name: Push
      run: |
       if [ -d "dist" ]; then
       git add dist -f
       fi
       git add .
       if [[ -n $(git status -s) ]]; then
       git commit -m 'Auto Push'
       git push origin master --force
       else
       echo "No changes detected, skipping push"
       fi